# Source: https://github.com/game-ci/documentation/blob/main/docs/github/activation.md
name: Acquire activation file (One time per repo)
on:
  workflow_dispatch:
jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
    - name: Request manual activation file
      id: getManualLicenseFile
      uses: game-ci/unity-request-activation-file@v2.0-alpha-1
      with:
        unityVersion: 2020.2.2f1

    - name: Expose as artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.getManualLicenseFile.outputs.filePath }}
        path: ${{ steps.getManualLicenseFile.outputs.filePath }}
